version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  backend:
    build: ./backend/ImageCropper.API
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=ImageCropperDb;User=sa;Password=Password123!;TrustServerCertificate=True"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

